version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-ecommerce
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Zaq12wsx1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ecommerce
      TZ: "Asia/Ho_Chi_Minh"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - e-commerce
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 384M
networks:
  e-commerce:
    driver: bridge
